<?php

namespace App\Exports;

use App\Models\ReplacementHistory;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithProperties;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Facades\Excel;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;

class ReplacementHistoryExport implements FromQuery, WithHeadings, WithMapping, WithStyles, WithTitle, WithProperties, ShouldAutoSize
{
    protected $search;

    public function __construct($search = null)
    {
        $this->search = $search;
    }

    public function query()
    {
        $query = ReplacementHistory::with(['user'])
            ->where('status', 'approved');

        if ($this->search) {
            $query->where(function($q) {
                $q->where('code_number', 'like', "%{$this->search}%")
                  ->orWhere('component_name', 'like', "%{$this->search}%")
                  ->orWhere('hm_km', 'like', "%{$this->search}%")
                  ->orWhere('notes', 'like', "%{$this->search}%");
            });
        }

        return $query->latest();
    }

    public function title(): string
    {
        return 'Historical Replacement';
    }

    public function properties(): array
    {
        return [
            'title'           => 'KISS - Historical Replacement Report',
            'company'         => 'KISS - Keep It Simple System',
            'subject'        => 'Replacement Activity Report',
            'category'       => 'Report',
            'created'        => now()->format('Y-m-d H:i:s'),
        ];
    }

    public function headings(): array
    {
        return [
            'Code Number',
            'HM Unit',
            'Date',
            'Activity',
            'Category',
            'Component',
            'PIC',
            'Status',
            'Created At',
        ];
    }

    public function map($history): array
    {
        return [
            $history->code_number ?: '-',
            $history->hm_km,
            $history->replacement_date->format('d M Y'),
            $history->notes ?: '-',
            $history->category ?: '-',
            $history->component_name ?: '-',
            $history->pic ?: '-',
            ucfirst($history->status),
            $history->created_at->format('d M Y H:i'),
        ];
    }

    public function beforeExport(Excel $excel)
    {
        $excel->sheet->insertNewRowBefore(1, 4);

        // Row 1: Title
        $excel->sheet->setCellValue('A1', 'KISS - Historical Replacement Report');
        $excel->sheet->mergeCells('A1:I1');
        $excel->sheet->getStyle('A1')->applyFromArray([
            'font' => [
                'size' => 18,
                'bold' => true,
                'color' => ['rgb' => '8B0A50'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);

        // Row 2: Subtitle
        $excel->sheet->setCellValue('A2', 'Replacement Activity Export');
        $excel->sheet->mergeCells('A2:I2');
        $excel->sheet->getStyle('A2')->applyFromArray([
            'font' => [
                'size' => 12,
                'italic' => true,
                'color' => ['rgb' => '666666'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
            ],
        ]);

        // Row 3: Metadata
        $user = Auth::user();
        $metaText = 'Export Date: ' . now()->format('d M Y H:i:s') . '  |  Generated by: ' . ($user->name ?? 'System') . '  |  Role: ' . ucfirst($user->role ?? 'N/A');
        $excel->sheet->setCellValue('A3', $metaText);
        $excel->sheet->mergeCells('A3:I3');
        $excel->sheet->getStyle('A3')->applyFromArray([
            'font' => [
                'size' => 9,
                'color' => ['rgb' => '999999'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
            ],
        ]);

        // Row 4: Empty separator
        $excel->sheet->getRowDimension(4)->setRowHeight(8);
    }

    public function styles(Worksheet $sheet)
    {
        $maroon = '8B0A50';
        $pinkBg = 'FDF4F5';

        // Calculate highest row for data styling
        $highestRow = $sheet->getHighestRow() > 4 ? $sheet->getHighestRow() : 4;

        return [
            // Header row (row 5 due to inserted title rows)
            5 => [
                'font' => [
                    'size' => 11,
                    'bold' => true,
                    'color' => ['rgb' => 'FFFFFF'],
                ],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => $maroon],
                ],
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                    'vertical' => Alignment::VERTICAL_CENTER,
                ],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => Border::BORDER_THIN,
                        'color' => ['rgb' => 'FFFFFF'],
                    ],
                ],
            ],

            // Data rows
            '6:' . $highestRow => [
                'font' => [
                    'size' => 10,
                ],
                'alignment' => [
                    'vertical' => Alignment::VERTICAL_CENTER,
                ],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => Border::BORDER_THIN,
                        'color' => ['rgb' => 'DDDDDD'],
                    ],
                ],
            ],

            // Alternating row background for readability
            'A6:I' . $highestRow => [
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => $pinkBg],
                ],
            ],

            // Status column - green background
            'H6:H' . $highestRow => [
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => 'E8F5E9'],
                ],
            ],

            // Center align columns
            'A5:A' . $highestRow => [
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                ],
            ],
            'C5:C' . $highestRow => [
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                ],
            ],
            'H5:H' . $highestRow => [
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                ],
            ],
            'I5:I' . $highestRow => [
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                ],
            ],
        ];
    }
}
